Explicitly check for root access in init script.

diff --git a/trunk/init/rdiff-web b/trunk/init/rdiff-web
--- a/trunk/init/rdiff-web
+++ b/trunk/init/rdiff-web
@@ -19,6 +19,14 @@ if [ -f /etc/init.d/functions ]; then
  . /etc/init.d/functions
 fi
 
+# This script won't be able to run without root privileges.
+USERNAME=`id -un`
+if [ "$USERNAME" != "root" ]; then
+   echo "Error: this script must be run as root."
+   exit 1
+fi
+
+
 # See how we were called.
 case "$1" in
    start)
